const { chromium } = require(process.env.PLAYWRIGHT || 'playwright');
const { dismissMormo } = require('./helpers.js');
(async () => {
  const browser = await chromium.launch(process.env.CHROME ? { executablePath: process.env.CHROME } : {});
  const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('file://' + process.env.GAME + '/index.html');
  await page.click('[data-action="new"]');
  await dismissMormo(page);
  await page.locator('[data-action="hire"]').first().click();
  await page.locator('[data-action="hire"]').first().click();
  await dismissMormo(page);
  const state = await page.evaluate(() => ({ phase: Game.state.phase, opening: Game.state.openingPrototype }));
  if (state.opening || state.phase !== 'mission') throw new Error('採用後に通常の作戦会議へ直行しない');
  if (await page.getByText(/勇者到着まで|本日、勇者襲来/).count()) throw new Error('撤廃した3日間の期限表示が残っている');
  if (await page.locator('[data-action="endday"], [data-action="openingbattle"]').count()) throw new Error('撤廃した日次操作が残っている');
  if (await page.locator('[data-action="missionpick"]').count() !== 3) throw new Error('通常の作戦3択が出ない');
  if (errors.length) throw new Error(errors.join('\n'));
  console.log('✓ 開幕3日間を挟まず通常ループへ入る');
  await browser.close();
})().catch(e => { console.error('✗ 失敗:', e.message); process.exit(1); });
