// 城下町の札（2026-09-12）：札が出る／建てる／銀行で借りる・返す／家計簿。390px で横に溢れない。
const { chromium } = require(process.env.PLAYWRIGHT || 'playwright');
const { autoDismissMormo, enterMissionPhase } = require('./helpers.js');
const path = require('node:path');
const ok = (c, m) => { if (!c) process.exitCode = 1; console.log((c ? '  ✓ ' : '  ✗ ') + m); };
(async () => {
  const b = await chromium.launch(process.env.CHROME ? { executablePath: process.env.CHROME } : {});
  const page = await b.newPage({ viewport: { width: 390, height: 844 } });
  const errs = []; page.on('pageerror', e => errs.push(e.message));
  await autoDismissMormo(page);
  await page.goto('file://' + process.env.GAME + '/index.html');
  await page.evaluate(() => localStorage.clear()); await page.reload();
  await page.locator('.slot-card [data-action="new"][data-slot="1"]').first().click();
  await page.locator('[data-action="hire"]:not([disabled])').first().click();
  await enterMissionPhase(page);
  await page.evaluate(() => { Game.state.gold = 60; Game.state.materials = 12; Game.state.conquest = 2; Game.state.turn = 3; App.render(); });
  await page.click('[data-action="castle"]');
  await page.click('[data-action="castletab"][data-tab="town"]');
  await page.waitForTimeout(100);
  ok(await page.locator('.town-panel').count() === 1, '城下町の札が開く');
  ok(/税収/.test(await page.locator('.town-summary').innerText()), `税収の一行（${(await page.locator('.town-summary').innerText()).replace(/\s+/g, ' ')}）`);
  ok(await page.locator('.town-card').count() === 6, '施設6つ');
  ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '390px で横に溢れない');
  if (process.env.SP) await page.screenshot({ path: path.join(process.env.SP, 'town-390.png'), fullPage: true });
  await page.locator('[data-action="townbuild"][data-id="market"]').click();
  await page.waitForTimeout(150);
  const after = await page.evaluate(() => ({ lv: Town.lv(Game.state, 'market'), gold: Game.state.gold, materials: Game.state.materials, tax: Town.taxPerSettle(Game.state) }));
  ok(after.lv === 1 && after.gold === 45 && after.materials === 9 && after.tax === 6, `市場を建てた（Lv${after.lv}・所持金${after.gold}・建材${after.materials}・税${after.tax}）`);
  ok(await page.locator('[data-action="townbuild"]:not([disabled])').count() === 0, '同じ決着ではもう建てられない（全部 disabled）');
  await page.locator('[data-action="townborrow"][data-amount="20"]').click();
  await page.waitForTimeout(150);
  ok(await page.evaluate(() => Game.state.town.debt === 20 && Game.state.gold === 65), '20G 借りた');
  ok(/借金/.test(await page.evaluate(() => document.querySelector('.hud').textContent)), 'HUD に借金が出る（畳んだ行の中）');
  await page.locator('[data-action="townrepay"]').last().click();
  await page.waitForTimeout(150);
  ok(await page.evaluate(() => Game.state.town.debt === 0 && Game.state.gold === 45), '全部返した');
  ok(errs.length === 0, `ページエラーなし${errs.length ? '：' + errs[0] : ''}`);
  await b.close();
  console.log(process.exitCode ? '失敗あり' : '全通過');
})().catch(e => { console.error(e); process.exit(1); });
